baseURL: "https://bsidesgrunn.org/"
languageCode: en-us
title: BSides Groningen
theme: default
params:
  slogan: BSides Groningen is an Information Security conference organized by the community for the community.
  mastodon: "https://infosec.exchange/@bsidesgrunn"