name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git for GitHub
        run: |
          git config --global user.name "BSides Groningen"
          git config --global user.email "info@bsidesgrunn.org"

      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          submodules: true

      - name: Set up Hugo
        env:
          HUGO_VERSION: 0.132.2
        run: |
          echo "installing hugo $HUGO_VERSION"
          curl -sL -o /tmp/hugo.deb \
          https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb && \
          sudo dpkg -i /tmp/hugo.deb && \
          rm /tmp/hugo.deb  

      - name: Publish
        env:
          REPOSITORY: "https://bsidesgrunn:${{ secrets.GITHUB_TOKEN }}@github.com/bsidesgrunn/bsidesgrunn.org.git"
        run: ./publish.sh
